#+BEGIN_HTML
---
layout: notes
---
#+END_HTML
#+TOC: headlines 4

Those are collections of advices and thoughts from various
sources.

* Anything You Want — Derek Sivers

  Most people don't know why they're doing what they're doing. They
  imitate others, go with the flow, and follow paths without making
  their own.

  Any time you think you know what your new business will be doing,
  remember this quote from Steve Blank: No plan survives first contact

  It's counterintuitive, but the way to grow your business is to focus
  entirely on your existing customers. Just thrill them, and they'll
  tell everyone.

  To me, ideas are worth nothing unless they are executed. They are just
  a multiplier. Execution is worth millions. Explanation:
  AWFUL IDEA = -1
  WEAK IDEA = 1
  SO-SO IDEA = 5
  GOOD IDEA = 10
  GREAT IDEA = 15
  BRILLIANT IDEA = 20
  NO EXECUTION= $1
  WEAK EXECUTION = $1000
  SO-SO EXECUTION = $10,000
  GOOD EXECUTION = $100,000
  GREAT EXECUTION = $1,000,000
  BRILLIANT EXECUTION = $10,000,000

  That's the Tao of business: Care about your customers more than about
  yourself, and you'll do well.

  See the customer tell the story himself in this great video: http://sivers.org/squid.

* The Creative Habit: Learn It and Use It for Life — Twyla Tharp

  Some people find this moment—the moment before creativity begins—so
  painful that they simply cannot deal with it. They get up and walk
  away from the computer, the canvas, the keyboard; they take a nap or
  go shopping or fix lunch or do chores around the house. They
  procrastinate. In its most extreme form, this terror totally paralyzes
  people.

  The most productive ones get started early in the morning, when the
  world is quiet, the phones aren’t ringing, and their minds are rested,
  alert, and not yet polluted by other people’s words.

  The real secret is that they do this every day. In other words, they
  are disciplined. Over time, as the daily routines become second
  nature, discipline morphs into habit.

  Creativity is a habit, and the best creativity is a result of good
  work habits. That’s it in a nutshell.

  In order to be creative you have to know how to prepare to be creative.

  If art is the bridge between what you see in your mind and what the
  world sees, then skill is how you build that bridge.

  A lot of habitually creative people have preparation rituals linked to
  the setting in which they choose to start their day. By putting
  themselves into that environment, they begin their creative day.

  To get the creative habit, you need a working environment that’s
  habit-forming.

  By making the start of the sequence automatic, they replace doubt and
  fear with comfort and routine.

  Solitude is an unavoidable part of creativity.

  The golfer Ben Hogan said, “Every day you don’t practice you’re one
  day further from being good.” If it’s something you want to do, make
  the time.

  Venturing out of your comfort zone may be dangerous, yet you do it
  anyway because our ability to grow is directly proportional to an
  ability to entertain the uncomfortable.

  Creativity is more about taking the facts, fictions, and feelings we
  store away and finding new ways to connect them. What we’re talking
  about here is metaphor. Metaphor is the lifeblood of all art.

* Bird by Bird: Some Instructions on Writing and Life — Anne Lamott

  Good writing is about telling the truth.

  Perfectionism is the voice of the oppressor, the enemy of the people.
  It will keep you cramped and insane your whole life, and it is the
  main obstacle between you and a shitty first draft.

  This is how it works for me: I sit down in the morning and reread the
  work I did the day before. And then I wool-gather, staring at the
  blank page or off into space. I imagine my characters, and let myself
  daydream about them. A movie begins to play in my head, with emotion
  pulsing underneath it, and I stare at it in a trancelike state, until
  words bounce around together and form a sentence. Then I do the menial
  work of getting it down on paper, because I’m the designated typist,
  and I’m also the person whose job it is to hold the lantern while the
  kid does the digging. What is the kid digging for? The stuff. Details
  and clues and images, invention, fresh ideas, an intuitive
  understanding of people. I tell you, the holder of the lantern doesn’t
  even know what the kid is digging for half the time—but she knows gold
  when she sees it.

  John Gardner wrote that the writer is creating a dream into which he
  or she invites the reader, and that the dream must be vivid and
  continuous.

  You write a shitty first draft of it and you sound it out, and you
  leave in those lines that ring true and take out the rest. I wish
  there were an easier, softer way, a shortcut, but this is the nature
  of most good writing: that you find out things as you go along. Then
  you go back and rewrite. Remember: no one is reading your first
  drafts.

  Everyone I know flails around, kvetching and growing despondent, on
  the way to finding a plot and structure that work. You are welcome to
  join the club.

* The Art of Learning: A Journey in the Pursuit of Excellence — Josh Waitzkin

  Tao Te Ching, and my life took a turn.

  the first step to mastering the zone is to practice the ebb and flow
  of stress and recovery. This should involve interval training as I
  have described above, at whatever level of difficulty is appropriate
  for the age and physical conditioning of the individual.

  Interval work is a critical building block to becoming a consistent
  long-term performer.
