name: Aurélien Bottazini
highlight: pygments
exclude: [deploy.sh, originaux, rsyncexclude, doc, node_modules, bower_components, config, lib, Capfile, docker-compose.yml, Gemfile, Gemfile.lock, s3_website.yml, .env, deploy.sh]
encoding: utf-8
markdown: kramdown
sass:
  style: compressed
  sass_dir: _sass
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-sitemap
  - jemoji
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
livereload: true
