#+BEGIN_HTML
---
layout: notes
---
#+END_HTML
#+TOC: headlines 4

* Introduction
  Course available on [[https://www.edx.org/][edX]]

  MITx: 11.132x Design and Development of Educational Technology

* Week 1 - Everything Old is New Again
  + Behaviorism
    The term behaviorism refers to the school of psychology founded by
    John B. Watson based on the belief that behaviors can be measured,
    trained, and changed.
  + Constructivism - /Piaget/
    Constructivism is a theory of knowledge that argues that humans
    generate knowledge and meaning from an interaction between their
    experiences and their ideas.
  + Constructionism - /Papert/ - Inspired by Constructivism
    Stresses the importance of tools.
    Constructivism advocates student-centred, discovery learning where
    students use information they previously know to acquire more
    knowledge. This is done through participation in project-based
    learning where students are able to make connections between
    different ideas and areas of knowledge that the teacher helps them
    to form

  Links:
  + [[http://learning.media.mit.edu/content/publications/EA.Piaget%2520_%2520Papert.pdf][Difference between Constructionism and Constructivism]]
  + [[http://www.marketplace.org/topics/education/learning-curve/classroom-tech-history-hype-and-disappointment][History of Tech]]
  + [[https://en.wikipedia.org/wiki/Constructivism_%2528philosophy_of_education%2529][Wikipedia Constructivism]]
  + [[https://en.wikipedia.org/wiki/Constructionism_%2528learning_theory%2529][Wikipedia Constructionism]]

* Week 2 – Into the deep end
**  /Teaching for understanding/
    [[http://www.nap.edu/catalog/9853/how-people-learn-brain-mind-experience-and-school-expanded-edition][How people learn]]
    [[http://www.ascd.org/publications/educational-leadership/feb94/vol51/num05/Putting-Understanding-Up-Front.aspx][Putting Understanding Up Front]]

    It is very different to truly understand something than to simply go
    through repeated trials and errors to find the solution to a
    problem.

  1. Generative topics.
     Not all topics (concepts, themes, theories, historical periods,
     ideas, and so on) lend themselves equally to teaching for
     understanding. For instance, it is easier to teach statistics and
     probability for understanding than quadratic equations
  2. Understanding goals.
     The trouble with generative topics is that they are almost
     too generative. Each topic offers the opportunity to develop many
     different understandings. To create focus, teachers have found it
     useful to identify a few specific understanding goals for a topic.
     It has also proven helpful to list these goals in phrases of the
     form. “Students will understand that ...” or “Students will
     appreciate that....”
  3. Understanding performances.
  4. Ongoing assessment.
    Traditionally, assessment comes at the end of a topic and focuses on
    grading and accountability. These are important functions in many
    contexts, but they do not serve students' learning needs. To learn
    for understanding, students need criteria, feedback, and
    opportunities for reflection from the beginning of and throughout
    any sequence of instruction.

**  /Cognitive tutors/

    [[http://www.educause.edu/library/resources/7-things-you-should-know-about-intelligent-tutoring-systems][7 Things You Should Know About Intelligent Tutoring Systems]]

    Abstract:
    An intelligent tutoring system is computer software designed to
    simulate a human tutor’s behavior and guidance. Because these
    systems are able to interpret complex student responses and can
    learn as they operate, they are able to discern where and why a
    student’s understanding has gone astray and to offer hints to help
    the student understand the material at hand. Intelligent tutors
    provide many of the benefits of a human tutor to very large
    numbers of students. Intelligent tutoring systems can also provide
    real-time data to instructors and developers looking to refine
    teaching methods.

* Week 3 - Just Do it
  “Getting the right answer through an efficient way”
  – Paul Horwitz

  Learn genetics through a game with dragons: [[http://geniverse.concord.org][Geniverse]]

  Sometimes it is hard to get “real” when you teach. Models are
  good but not enough. It is important to put it in a real world
  context.
  Some people (most?) need reflections after game play.

  Constructivism: constructing your own knowledge while
  constructing a thing.

  Sometimes we teach something so well we forget what it is like
  to learn for the first time.

  Teachers may be afraid to engage in active learning because
  they are afraid to not know all the answers. Often students are
  more resourceful that what we might expect.

  Simulations & active learning: [[http://phet.colorado.edu][Phet]]

  [[http://www.makeymakey.com][MakeyMakey]]: creative controls. Physical world meets online world

  [[http://buildinprogress.media.mit.edu][BuildInProgress]] documents the whole process to build something
  [[http://llk.media.mit.edu][Lifelong Kindergarten]]


  Build grit in learners (related to growth mindset)

  Non cognitive skills:
  + Grit
  + Passion
  + Perseverance


  Keep people at the edge of their ability i.e —zone of proximal
  development—

  In games:
  + What is interesting in this?
  + What is fun in this?


  Active Learning is
  1. Doing things
  2. Reflection
** Elevator Pitch


   http://successwise.com/crafting-your-elevator-pitch
   http://www.mindtools.com/pages/article/elevator-pitch.htm
* Week 4 - Strength in numbers
** [[http://en.wikipedia.org/wiki/List_of_virtual_communities_with_more_than_1_million_users][Communities of practice]]
    Group of people interested in learning the same thing

    It is the intersection between interests, Academics and Peer
    culture.
    We find meaning when learning with pears

    [[http://labyrinth.thinkport.org/www/educators.php][Lure of the Labyrinth]]: middle-school pre-algebra.

    We learn in interaction with others.

** Learn programming

   Read Book.
   Stack Overflow.
   Algorithms.
   Design Patterns.
   Programming contests

** Games
   THey keep mentionning games with collaborative learning

   /Vanished/ was a learning experience designed by the MIT where
   students solved together a mistery by interactiving togethers
   and with researchers (in contrast with getting a lecture from
   them).
   And scientist were threated like rockstars!

** MOOC

   Massive Open Online Course

   + Coursera
   + Edx
   + p2pu
* Week 5 - Put It To The Test
  An assessment is to test students on what they know and on what they
  can do.

  An assessment can be

  - /Formative/ :: provides feedback to improve learning experience
  - /Summative/ :: ex: midterm
  - a /performance/ assessment :: focus on task and how students
       perform on an activity. Application of knowledge

  An assessment can be summative, formative and check performance at
  the same time.

  In a game it is hard to distinguish learning from assessment.
  /Rise of Nations/ is a game with good graphs at the end of battles.

  Teaching for solving problems is much better than regular
  assessments.

  We should view assessments viewed as a process rather than a thing.
  If we can forget grades, we can focus assessment comments on what
  students should do next.
  /Stealth assessment/: An assessment where you blur the frontier
  between learning and the actual test.

  It is evolving but we are still only adapting what we have on
  textbooks. There’s not much large scale change yet.

  Assessment qualities:
  + Fairness
  + Validity
  + Reliability
  + Comparability

  If an assessment is too open minded, students get lost.
  Grit is a great predictor of success.

  Be careful on what you measure.
  Choose to engage in critical thinking. It is very different than
  just doing trial and error.

  Future of assessments: data mining and data analysis.
  The real challenge is to find what is important.

  Links:
  + http://www.edudemic.com/the-6-types-of-assessments-and-how-theyre-changing/
  + https://www.radixendeavor.org/
  + http://www.glasslabgames.org/
  + http://www.simscientists.org/home/index.php
  + http://aaalab.stanford.edu/
  + http://www.corestandards.org/

* Week 6 - The Proof is in the pudding

  /Design Based Research/ is a systematic but flexible methodology
  aimed to improve educational practices through iterative analysis,
  design, development, and implementation, based on collaboration
  among researchers and practitioners in real-world settings, and
  leading to contextually-sensitive design principles and theories

  /DBR/ takes an idea and iterates on that idea. It is important to
  take context into consideration

  /DBIR/ stands for design based implementation research. It is /DBR/
  going out in the world. /DBIR/ starts with /DBR/ and tries to recast
  it into something possible in the real world.

  With /DBR/, researchers are not the users. Teachers and students are.

  Links:
  + http://www.brainpop.com/educators/community/whygames/
  + http://www.learndbir.org/
  + http://education.mit.edu/projects/biograph
