#+BEGIN_HTML
---
layout: notes
---
#+END_HTML
#+TOC: headlines 4

* Session 1 - Course Intro

  Explain this is all about learning how to
  communicate with each other.

  Thus, It is not going to be a lecture. We are going to have *conversations*.

  Commitment: We are going to share Real life examples in each session. Everyone
  should have at least one story to share for each session.
  Commitment: Takes notes.
  Commitment: Share all notes at the end of the course.

  Project final goal: Mood pull request for the commitment project. (Nazar PR will be on trust)

  One or Two chapters to read between each session.
  2 weeks between sessions.

** Homework
  Ask everyone to think of 1 or 2 example they can share about chapter 1 and 2.

* Session 2 - Conversation for *action* 1, Habits, Create Value

** Chapter 1

   Responsibility: Nobody charged with taking care of the problem.
   Discussions not really solving anything. -> Share daily stand-ups story.
   Bad technical leaders _terrorizing_ others. Share http://contributor-covenant.org/

   -> Commitments to each others

   Commitments happen in conversations -> Manage conversations instead of information.
   Eg. Client may not know what he wants

   Basic structure of a conversation for action
   1. Request or offer
   2. Promise or acceptance
   3. Declaration of completion -> Don't forget to communicate
   4. Declaration of satisfaction.

   Unfulfilled promises and unnecessary requests can destroy trust between
   people. (more on trust later)

** Chapter 2

   Work that creates value vs bureaucratic ware
   Teamwork vs autonomy -> prs
   Same understanding of the problem
   How to build stronger relationships

   Miscoordination -> destroys trust (more on trust later)

   How to improve habits? -> Share my Morning routine, share my sketch-note habit (66 days)

** Homework

   Read chapter 3 and 4.
   Story to share

* Session 3 - Conversation for *action* 2

** Chapter 3

   Basic structure of a conversation for action
   1. Request or offer
   2. Promise or acceptance
   3. Declaration of completion -> Don't forget to communicate
   4. Declaration of satisfaction.

   We do this to observe what we produce in speaking with the other person

   Everything we speak about is designed around customer satisfaction -> share
   Derek Sivers story about the person is hired to do the mp3 import task. Task
   he did not do, doing other things this person considered important, even
   though he was hired just for this.

** Chapter 4

    Conversation for possibilities are here to declare things you like, what
    kind of person you are, what role you are willing to play, the career you
    will follow, projects you will undertake. -> share my objectives

    Declare a break. Declare possibility.

** Homework

   Read chapter 5
   Story to share
   Reminder: Be prepared to share your notes by the end of the course.

* Session 4 - Assertions and Assessments

** Chapter 5 - Assertions and Assessments

  When we work we are constantly assessing our work and the work of others

  Make assessments about the future, don't try to predict it -> share: less stress

  Try to be open to all possibilities. This can be done by gathering all the
  information you need. BUT don't forget to take action

  By making assessments and assertions, you coordinate your actions.

  Assertion -> can be seen
  Assessment -> verdicts

  Importance of standards to judge our work and to assess satisfactory
  performance. They must be shared by all.

  !! Resignation = Decide there is not hope in changing the future. Very dangerous.

  Try to break ungrounded assessments.

  *This is the end of part 1 of the book*

** Homework
   Chapter 6 and Chapter 7
   Story to share

* Session 6 - Characterization and mood

** Chapter 6

   Well-grounded assessments allow us to give and receive opinions from others
   about our work and ourselves. -> share story on how to walk with someone
   difficult to work with.

   Characterization is a conversation.

   When we speculate about how a person will act, we make a characterization.

   A characterization is well grounded when:
   - You supply assertions about specific actions a person has repeted several times
   - You are aware your characterization speculates about how that person will
     act in the future.

   Characterization don't settle permanent levels of competence. We can take
   action to change our competence.

** Chapter 7

   Most people can't change their mood -> permanent lifestyle.
   Here we think of mood as how people's experiences predispose them to
   certain actions.

   Can't undo the past, so focus on the future -> and also the present.

   Take moods out of the personal level, subjective realm and into the realm of assessment

   Negative mood/assessment -> ungrounded  -> break the mood.

   Guideline to manage negative moods:
   - Awareness
   - Choice
   - Investigation
   - Plan for action

** Homework
   Chapter 8
   Story to share

* Session 7 - Trust

** Chapter 8

   Trust is crucial both with your teammates and with clients.
   -> share pragmatic programmer story where you protect your coworker mistake
   -> share story where I bought a book for the client.

   Tips for building trust:
   - show concern
   - manage your commitments rigorously

   Trust is rarely a conscious decision but an undifferentiated attitude about a person.

   Fundamental of trust:
   - Sincerity
   - Competence
   - Reliability
   - Engagement

   Don't be a slave to your promises

** Homework
   Chapter 9
   Story to share
   Reminder: Have your notes ready next time. We are going to share them between us.

* Session 8 - Building and leading teams

** Chapter 9

   Build teams through right conversations at the right time. -> share: take this
   course as an example

   Two central claims:
   - Leadership is a phenomenon of the conversations of a team, not an
     individual. A leader ensures the conversations are assessed but the team to
     be effective.
   - All member of the team commit to the same mission and to coordinate
     conversations to fulfill the mission.

   Nice commitments
   1. Coordinate action for the sake of a shared, explicitely declared mission
   2. Own the shared mission
   3. Fulfill roles by each member of the team. Explicit accountabilities
   4. Develop and carry on practices for anticipation
   5. Unity of comment. Political declarations of the team
   6. Evoke and produce trust
   7. Mood
   8. Team's standards for assessment
   9. Future of the company, the team and people's careers.

   A leader should put together and orchestrate a theam that has strong competencies
   A leader should build alliances

   Those are qualities you can acquire in time.

   *Exchange notes*

** Homework
   Review each other notes
   Mood/Trust PR on GitHub repo for commitment project

  *End of part 2 and End of Course*
