#+BEGIN_HTML
---
layout: notes
---
#+END_HTML
#+TOC: headlines 4

* Introduction
  Fight your fear, stop procrastination, follow your passions, do
  what's important.

  http://theflinch.com/

* Highlights
+ The Flinch is your real opponent, and information won't help you
   fight it.
+ Facing the flinch is hard. It means seeing the lies you tell
  yourself, facing the fear behind them, and handling the pain that
  your journey demands–all without hesitation.
+ It's why you can't quit your job or be the person you want to
  be–you can't see the flinch in yourself. The flinch is why you don't
  do the work that matters, and why you won't make the hard decisions.
+ Have you ever asked yourself why your stomach tenses up and you
  can't watch imaginary characters on a television screen do awkward,
  embarassing things? You should.
+ Think of a bear. You see it, and you react, instantly. You know
  how to deal because your brain is built to help you survive it: you
  run, jump, fight, or hide. But that's not the world you're in, so
  instead, flinching happens at job interviews or when you're asking a
  girl to the prom. Those things get magnified. Your privileged-world
  problems become the bear, and you treat them that way.
+ The lessons you learn the best are those you get burned by.
  Without the scar, there's no evidence or strong memory.
+ The anxiety of the flinch is almost always worse than the pain
  itself. You've forgotten that. You need to learn it again. You need
  more scars. You need to live.
+ Ask yourself this: would your childhood self be proud of you, or embarrassed?
+ Ralph Waldo Emerson said. “Do not go where the path may lead; go
  instead where there is no path and leave a trail.”
+ Nothing will actually happen if you stop being afraid. You're free.
+ Everything that you are used to, done long enough, starts to
  seem natural, even though it might not be.
+ *Train yourself to flinch forward, and your world changes radically.*
+ Flinch forward in nature, at home, in your workplace, anywhere.
  Try whatever you like or find interesting. Climb trees, eat new
  food, or learn to dance. All are provocations to the status quo that
  you use as stepping stones to larger explorations.
+ *Fact: those who face the flinch make a difference. The rest do
  not.*
+ Today, right now, eliminate all excuses from your vocabulary.
  Refuse to mince words or actions. Refuse a scar-free life.
+ Whatever you are used to, whether cigarettes, shopping, or
  twitter, must be eliminated in the quest to get into the ring. You
  must make a sacrifice on the altar of greatness and perform acts
  that others will not.

  If you aren't willing to sacrifice your comfort, you don't have what
  it takes

  Set fire to your old self. It's not need here. It's too busy
  shopping, gossiping about others, and watching days go by and asking
  why you haven't gotten as far as you'd like. This old self will die
  and be forgotten by all but family, and replaced by someone who
  makes a difference.
+ *Stop flinching. Speak up. Join us.*
+ In contrast, there is only one way to do it right and to see the
  truth. It is to look at these ways of acting in yourself or others
  and cross through their verbal defenses, and not to believe them at
  all.
+ But the solution is always the same: ruthless yet compassionate
  honesty in the face of all the lies you tell yourself.
+ There are enough viewers. There are enough cheerleaders. There
  are enough coaches and enough commentators. What there isn't enough
  of are players.
+ *Don't ever be afraid again*
+ If you think you can do it, or you think you can't do it, you
  are right. –– Henry Ford
+ My favorite movie of all times is The Matrix. I like the movie
  not only for the amazing special effects and action scenes, but for
  it's insight in human condition. I believe we live in the Matrix. I
  believe the matrix is very real. We may not be the unconscious
  batteries living in the delusion of the programs created by the
  machines, but we live in the delusion of the rules and belief
  systems created by our parents , teachers, colleagues, bosses, and
  society designed to control us.
+ My mission in my life is to listen to my own voice as much as
  possible and follow my instincts.

* The Flinch, A checklist
  1. Challenge yourself by doing things that hurt, on purpose.
     Have a willpower practice, such as very hard exercise,
     meditation, endurance, or cold showers. Choose something that
     makes your brain scream with how hard it is, and try to tolerate
     it. The goal isn't just to get used to it. It's to understand
     that pain is something you can survive.
  2. Remember things that are easy to forget. Upgrade your current
     relationships. Create un-birthdays for your friends and stick to
     them. Go through old text messages to rekindle dormant
     friendships. It can be awkward, but that's the point. You will
     make an impact by choosing to do what makes others nervous.
  3. Read more. Not just current blog posts and tweets and
     Facebook updates online, but other sources that take more
     consideration than blog posts or news. Find thorough and in-depth
     analyses of subjects you find interesting, or irreverent stuff
     that makes you feel alive. Read things you disagree with. Read
     things that are too difficult to understand, and then overcome
     your discomfort by pushing yourself to understand them.
  4. Get some scars by working with your hands. Try to understand
     how things in your world work, like your car, your stereo system,
     or even your kitchen. Have a garden or a dog to help you stay
     grounded in the real world.
  5. Turn your mobile phone off for a few hours each day. Having
     nothing to do while you're waiting for a bus can be boring, but
     it's only when you're bored that the scary thoughts come to the
     surface. Use a dumb phone on the weekends to prevent yourself
     from checking your messages.
  6. Find new friends who make you feel uncomfortable, either
     because they have done more than you or because they have done
     nothing that you have. Meet tattoo artists or homeless people,
     millionaires or best-selling authors. Host dinner parties for
     them. Serve them bizarre food. Why the hell not?
  7. Renegotiate your work. If you achieve X, then will your
     employer do Y? Ask beforehand and deliver, or if you can't get
     permission, go for it anyway and ask for forgiveness. Create a
     new job title for yourself; then carve out the job.
  8. Start dressing as if you had a very important job or meeting,
     or as if you were twenty years old again and thought you were the
     coolest person on Earth. What would you do differently? How would
     people treat you once you did?
  9. Imagine that you have to leave a legacy, and everyone in the
     world will see the work you've done. Volunteer. Create something
     that lasts and that can exist outside of you, something that
     makes people wonder and gasp. Build a support structure for
     others. Devote some of your time or money to it.
  10. Make something amazing, something that's terrifying to you.
      Stay uncomfortable. Fight the flinch wherever you see it. Leave
      no stone unturned.
