#+BEGIN_HTML
---
layout: notes
---
#+END_HTML
#+TOC: headlines 4

* Introduction
  http://personalmba.com/
* Inspiring Quotes

  + Self-education is, I firmly believe, the only kind of education
    there is. — Isaac Asimov, former professor of biochemistry at boston university and author of over five hundred books
  + Whoever best describes the problem is the one most likely to solve
    it. — Dan Roam, author of the back of the napkin
  + You wasted $150,000 on an education you could have got for a buck
    fifty in late charges at the public library. — Matt Damon as will hunting, good will hunting
  + So often people are working hard at the wrong thing. Working on
    the right thing is probably more important than working hard. —
    Caterina Fake, founder of flickr.com and hunch.com
  + I have not failed. I’ve just found 10,000 ways that won’t work.
    — Thomas A. Edison, prolific inventor
  + I can’t give you a surefire formula for success, but I can give
    you a formula for failure: try to please everybody all the time.
    — Herbert Bayard Swope, pulitzer prize–winning journalist
  + In an attention economy (like this one), marketers struggle for
    attention. If you don’t have it, you lose. — Seth Godin,
    best-selling author of permission marketing, purple cow, and
    tribes
  + Before every action, ask yourself: Will this bring more monkeys on
    my back? Will the result of my action be a blessing or a heavy
    burden? — Alfred A. Montapert, author of the supreme philosophy of
    man: the laws of life
  + Remarkability Advertising is the tax you pay for being
    unremarkable. — Robert Stephens, founder of geek squad
  + Everything we hear is an opinion, not a fact. Everything we see is
    a perspective, not the truth. — Marcus Aurelius, roman emperor and
    philosopher
  + Conservation of Energy Whenever an individual or a business
    decides that success has been attained, progress stops.
    — Thomas J. Watson, former president of IBM
  + If you had to identify, in one word, the reason why the human race
    has not achieved, and never will achieve, its full potential, that
    word would be: “meetings.”
    — Dave Barry, comedian and newspaper columnist
  + Goods in any storehouse are useless until somebody takes them out
    and puts them to the use they were meant for. That applies to what
    man stores away in his brain, too.
    — Thomas J. Watson, former president of IBM

* Companies
  Large companies move slowly. Good ideas often died on the vine
  simply because they had to be approved by too many people.

  Climbing the corporate ladder is an obstacle to doing great
  work. I wanted to focus on getting things done and making
  things better, not constantly positioning myself for promotion.
  Politics and turf wars are an inescapable part of the daily
  experience of working for a large company. 3. Frustration leads
  to burnout. I wanted to enjoy the daily experience of work, but
  instead I felt like I was running a gauntlet each day. It began
  to affect my health, happiness, and relationships. The longer I
  stayed in the corporate world, the more I realized I wanted
  out. I desperately wanted to work on my own terms, as an
  entrepreneur.

  Less skilled managers are actually more likely to be rewarded,
  since everyone can see them “making things happen” and “moving
  heaven and earth” to resolve issues—issues they may have created
  themselves via poor management.

  Congratulations: you’ve used your intelligence and drive to
  condemn yourself to the life of an indentured servant.

* Accounting

  + Accounting Made Simple by Mike Piper
  + Essentials of Accounting by Robert N. Anthony and Leslie K.
    Breitner
  + The McGraw-Hill 36-Hour Course in Finance for Nonfinancial
    Managers by Robert Cooke
  + How to Read a Financial Report by John A. Tracy.

* Schools

  Business schools don’t create successful people. They simply
  accept them, then take credit for their success.

  If you get in, the school will do what it can to help you get a
  decent job, but making things happen will always be your
  responsibility.

  The one significant benefit that business schools do provide is
  better access to Fortune 50 recruiters, consulting firms, large
  accounting firms, and investment banks via on-campus recruiting
  and alumni networks.

* Product & Ideas

  If you find something broken that you can fix for a lot of people,
  you’ve found a gold mine.

  If you discover that you have what people want, great—full steam
  ahead. If there’s no demand for what you’re developing, you can
  quickly and cleanly move on to the next promising idea.

  If you’re not embarrassed by the first version of your product,
  you’ve launched too late.

  Developing and testing a Minimum Economically Viable
  Offer (MEVO) is important: it’s the best way to determine
  whether or not you’ve created something valuable enough to sell
  before you invest your life savings.

* Business

  No business plan survives first contact with customers.

  Business is about creating and delivering value to paying
  customers, not orchestrating legal fraud. Unfortunately for us
  all, business schools have de-emphasized the former in favor of
  teaching the latter.

  Roughly defined, a business is a repeatable process that:

  1. Creates and delivers something of value
  2. That other people  want or need
  3. At a price they’re willing to pay
  4. In a way that satisfies the customer’s needs and expectations
  5. So that the business brings in enough profit to make it
     worthwhile for the  owners to continue operation.

  Every successful business actually delivers what it promises to
  its customers.

  HERE’S WHAT MAKES A BUSINESS RESILIENT:
  — Low (preferably zero) outstanding debt
  — Low overhead, fixed costs, and operating expenses
  — Substantial cash reserves for unexpected contingencies
  — Multiple independent products/industries/lines of business
  — Flexible workers/employees who can handle many responsibilities
  well
  — No single points of failure —Fail-safes/backup systems for all core processes

* Competition

  Learn everything you can from your competition, and then create
  something even more valuable.

  Don’t focus on competing. Focus on delivering even more value. Your
  competition will take care of itself.

* Marketing

  Without Marketing, no business can survive—people who don’t know
  you exist can’t purchase what you have to offer, and people who
  aren’t interested in what you have to offer won’t become paying
  customers.

  Marketing is about getting noticed.
  Sales is about closing the deal.

  Rule #1 of Marketing is that your potential customer’s available
  attention is limited.

  In order to be noticed, you need to find a way to earn that
  attention by being more interesting or useful than the competing
  alternatives.

  If you want to attract Attention quickly, give something valuable
  away for Free.

  Here’s an example: Almost everyone will ignore postal junk mail—if
  it looks blatantly commercial or mass-produced, there’s a 99
  percent chance the recipient will throw it away without a second
  thought. Change the form, however, and Receptivity changes as
  well. Most people will at least open a hand-addressed envelope,
  since it’s clear someone spent time and effort sending it to them.
  Taken to an extreme, almost everyone (including busy executives)
  will open and look through the contents of a large overnight
  hand-addressed FedEx envelope—it’s big, expensive, and clearly
  requires effort to send. Even then, if the contents don’t match
  what they’re interested in, you’ll lose their attention
  immediately.

  Being Remarkable is the best way to attract Attention. In the
  classic marketing book Purple Cow, Seth Godin uses a wonderful
  metaphor to illustrate this principle. A field full of brown cows
  is boring. A purple cow violates the viewer’s expectations, which
  naturally attracts Attention and interest.

  Attempting to appeal to everyone is a waste of time and money:
  focus your marketing efforts on your Probable Purchaser.

  Marketing is most effective when it focuses on the desired End
  Result

  Your job as a marketer isn’t to convince people to want what
  you’re offering: it’s to help your prospects convince themselves
  that what you’re offering will help them get what they really
  want.

  Framing is the act of emphasizing the details that are critically
  important while de-emphasizing things that aren’t, by either
  minimizing certain facts or leaving them out entirely.

  A Hook is a single phrase or sentence that describes an offer’s
  primary benefit.

  Ensure that every message you create has a clear Call-To-Action,
  and you’ll dramatically increase the effectiveness of your
  marketing activities.

  Used constructively, Controversy can be an effective way to
  attract Attention

  Building your Reputation takes time and effort, but it’s the most
  effective kind of marketing there is.

  Add a bit of Social Proof to your offers, and your sales will
  soar.


** Contrast
   Contrast is often used to influence buying decisions.

   Take advantage of Contrast when presenting your offer, and you’ll
   increase the odds that your potential customers will view your
   offer favorably.

** Sales Objections
   There are five standard objections that appear in sales of all
   kinds:

   Objection #1 (“it costs too much”) is best addressed via Framing
   and Value-Based Selling.

   Objections #2 and #3 (“it won’t work” / “it won’t work for me”)
   are best addressed via Social Proof—showing

   Objections #4 and #5 (“I can wait” / “it’s too difficult”) are
   best addressed via Education-Based Selling.

   Loss Aversion is the idea that people hate to lose things more
   than they like to gain them.

   The best way to overcome Loss Aversion is to Reinterpret the risk
   of loss as “no big deal.”

   Eliminate this perception of risk by offering a money-back
   guarantee or similar Risk Reversal offer, and people will feel the
   decision is less risky, resulting in more sales.

** Scarcity
   Scarcity encourages people to make decisions quickly. Scarcity is
   one of the things that naturally overcomes our tendency to
   conserve—if you want something that’s scarce, you can’t afford to
   wait without the risk of losing what you want.

   As a result, adding a Scarcity element to your offer is a great
   way to encourage people to take action.

   1. Limited Quantities—inform prospects that you’re offering a limited number of units for sale.
   2. Price Increases—inform prospects that the price will go up in the near future.
   3. Price Decreases—inform prospects that a current discount will
   end in the near future. 4. Deadlines—inform prospects that the
   offer is only good for a limited period of time.

   Add an element of Scarcity to your offer, and you’ll encourage
   people to buy now instead of “later.”

** New
   Novelty—the presence of new sensory data—is critical if you want
   to attract and maintain attention over a long period of time. One
   of the reasons people can focus on playing games or surfing the
   Internet for hours at a time is novelty—every new viral video,
   blog post, Facebook update, Twitter post, and news report
   reengages our ability to pay attention.

   Continue to offer something new, and people will pay attention to
   what you have to offer.

* Customers

  Screening your customers can help you filter out the bad customers
  before they do business with you.

  Attracting your Probable Purchaser’s Attention immediately after
  they’ve reached the Point of Market Entry is hugely valuable.

  If you can get a prospective customer’s attention as soon as they
  become interested in what you’re offering, you become the standard
  by which competing offers are evaluated.

  Addressability is a measure of how easy it is to get in touch with
  people who might want what you’re offering.

  If you encourage your prospects to Visualize what their life will
  look like after purchasing, you increase the probability that
  they’ll purchase from you.

  Permission is a real asset. Reaching new people tends to be
  difficult and expensive. It’s far easier to follow up with someone
  you already know—all

  Before asking your prospects for Permission to follow up, make it
  clear what they’ll be getting and how it’ll benefit them.

  Tell your prospective customers the stories they’re interested in
  hearing, and you’ll inevitably grab their Attention.

  Building a trustworthy Reputation over time by dealing fairly and
  honestly is the best way to build Trust.

  Education-Based Selling is the process of making your prospects
  better, more informed customers.

  Reactivation is the process of convincing past customers to buy
  from you again.

  Make it a priority every three to six months to contact your
  lapsed customers with another offer to see if you can encourage
  them to start buying again, and you’ll be amazed by the results.

  Lifetime Value is the total value of a customer’s business over
  the lifetime of their relationship with your company. The more a
  customer purchases from you and the longer they stay with you, the
  more valuable that customer is to your business.

  Once you understand the Lifetime Value of a prospect, you can
  calculate the maximum amount of time and resources you’re willing
  to spend to acquire a new prospect.

  Perceptual Control represents a fundamental shift in understanding
  why people do the things they do. Once you understand that people
  act to control their perceptions, you’ll be better equipped to
  influence how they act.


** Allowable Acquisition Cost
   Allowable Acquisition Cost (AAC) is the marketing component of
   Lifetime Value. The higher the average customer’s Lifetime Value,
   the more you can spend to attract a new customer, making it
   possible to spread the word about your offer in new ways.

   To calculate your market’s Allowable Acquisition Cost, start with
   your average customer’s Lifetime Value, then subtract your Value
   Stream costs—what it takes to create and deliver the value
   promised to that customer over your entire relationship with them.
   Then subtract your Overhead (discussed later) divided by your
   total customer base, which represents the Fixed Costs (discussed
   later) you’ll need to pay to stay in business over that period of
   time. Multiply the result by 1 minus your desired Profit Margin
   (if you’re shooting for a 60 percent margin, you’d use 1.00 - 0.60
   = 0.40), and that’s your Allowable Acquisition Cost. Here’s an
   example: if your average Lifetime Value is $2,000 over a five-year
   period, and the cost of Value Creation and delivery is $500, that
   leaves you with $1,500 in revenue per customer served. Assuming
   your Overhead expenses are $500,000 over the same five-year period
   and you have 500 customers, your Fixed Costs are $1,000 per
   customer, which leaves you with $500 in revenue before marketing
   expenses. Assuming you’re shooting for a minimum 60 percent profit
   margin, you can afford to spend 40 percent of that $500 on
   marketing, which gives you a maximum AAC of $200 per customer.

* Not perfect

  Reciprocation is the strong desire most people feel to “pay back”
  favors, gifts, benefits, and resources provided.

  Ben and Betty, made sure to notify us of two important facts about
  our new home: (1) Rock slides were a very real possibility. (2)
  Black bears and mountain lions roamed nearby.

  Counterintuitively, making a Damaging Admission like this to your
  prospects can actually increase their Trust in your ability to
  deliver what you promise.

  Your prospects know you’re not perfect, so don’t pretend to be.

* Generous

  Being generous is one of the best things you can do to improve
  your results as a salesperson.

  Yes, you’ll lose money on customers who are obviously taking
  advantage of your generosity, and that never feels good. In
  compensation, by eliminating the risk that every purchaser feels,
  you’ll close many more sales and come out way ahead in terms of
  total revenue and profit.

* Price

  If you expect people to pay you perfectly good money to buy what
  you’re offering, you must be able to provide a Reason Why the
  offered price is worth paying.

  There are four ways to support a price on something of value:
  1. replacement cost :: The Replacement Cost method supports a price
       by answering the question “How much would it cost to replace?”
  2. market comparison :: The Market Comparison method supports a
       price by answering the question “How much are other things like
       this selling for?”
  3. discounted cash flow / net present value :: The Discounted Cash
       Flow (DCF) / Net Present Value (NPV) method supports a price by
       answering the question “How much is it worth if it can bring in
       money over time?”
  4. value comparison :: The Value Comparison method supports a price
       by answering the question “Who is this particularly valuable
       to?”

  Value Comparison is typically the optimal way to price your offer,
  since the value of an offer to a specific group can be quite high,
  resulting in a much better price. Use the other methods as a
  baseline, but focus on discovering how much your offer is worth to
  the party you hope to sell it to, then set your price
  appropriately.

  Value-Based Selling is the process of understanding and
  reinforcing the Reasons Why your offer is valuable to the
  purchaser.

  If you discover why, how, and how much your offer will benefit the
  customer, you’ll be able to explain that value in terms they’ll
  understand and appreciate. Understanding the value you can provide
  your customers is the golden path to a profitable sale.

* Negotiation

  There are always many paths to a successful Transaction, which is
  the essence of negotiation. Negotiation is the process of
  exploring different options to find Common Ground.
  Your Next Best Alternative is what you’ll do in the event you
  can’t find Common Ground with the party you’re negotiating with.

  In every negotiation, there are Three Universal Currencies:
  resources, time, and flexibility.

  Keep the Three Universal Currencies in mind when negotiating,

  The Three Dimensions of Negotiation are setup, structure, and
  discussion.

  Setup: setting the stage for a satisfying outcome to the
  negotiation.

  Structure: the terms of the proposal. In this phase, you put
  together your draft proposal in a way they’re likely to appreciate
  and accept:

  Discussion: actually presenting the offer to the other party.

  A Buffer is a third party empowered to negotiate on your behalf.
  Agents, attorneys, mediators, brokers, accountants, and other
  similar subject-matter experts are all examples of Buffers.

  As a rule of thumb: don’t give anyone unfettered control over
  decisions that directly affect your money.

  Buffers can be a hugely valuable resource as long as you’re clear
  about how they’ll be rewarded, what they’re responsible for, and
  how you intend to work together.

* Value, Quality, Expectations

  Value Delivery involves everything necessary to ensure that every
  paying customer is a happy customer: order processing, inventory
  management, delivery/fulfillment, troubleshooting, customer
  support, etc. Without Value Delivery, you don’t have a business.

  A Value Stream is the set of all steps and all processes from the
  start of your Value Creation process all the way through the
  delivery of the end result to your customer. Understanding what
  your offer’s Value Stream looks like is critically important if
  you want to be able to deliver value to your customers quickly,
  reliably, and consistently.

  A customer’s perception of quality relies on two criteria:
  expectations and performance. You can characterize this
  relationship in the form of a quasi-equation, which I call the
  Expectation Effect: Quality = Performance - Expectations.

  The best way to consistently surpass expectations is to give your
  customers an unexpected bonus in addition to the value they
  expect.

  Every improvement you make to your Value Stream make it harder for
  potential competitors to keep up.

  Incremental Augmentation is an example of the power of
  Accumulation. If your offer improves with every Iteration Cycle,
  it won’t be long before your offer is many times more valuable to
  your customers than it was before.

  That’s Amplification: making a small change to a scalable System
  produces a huge result.

* Scam Artist

  There’s a term for a person who takes other people’s money without
  delivering equivalent value: “scam artist.”

* Distribution channel
  A Distribution Channel describes how your form of value is
  actually delivered to the end user.

  strategy—if you’re working with multiple Distribution Channels,
  plan to devote time and energy to making sure they’re representing
  your business well.

* Contractors

  Contractors are notoriously unpredictable: they often show up
  late, take too long, do sloppy work, and have bad attitudes. The
  secret of Aaron and Pat’s success is Predictability—they do great
  work every single time, deliver on schedule, and they’re always
  pleasant to work with.

* Predictability

  There are three primary factors that influence the Predictability
  of an offer:
  1. uniformity :: Uniformity means delivering the same
                   characteristics every time.
  2. consistency ::
  3. reliability :: Reliability means being able to count on delivery
                    of the value without error or delay.

* You
  There are two primary ways to Externalize your thoughts: writing
  and speaking.

  Reinterpret your past, and you’ll enhance your ability to make
  great things happen in the present.

  Eliminate the inner conflicts that compel you to move away from
  potential threats, and you’ll find yourself experiencing a feeling
  of Motivation to move toward what you really want.

  Inhibition is the ability to temporarily override our natural
  inclinations. If you’ve ever put up with one of your siblings (or
  colleagues) acting immature, obnoxious, or annoying, Inhibition
  prevented you from doing something you would have regretted later.

  Dr. Mischel found a correlation between Willpower and success:
  kids with a greater ability to “defer gratification” were more
  successful in school, as well as later on in life.

  Our reserves of Willpower are very limited and become Depleted
  with use.

  Willpower for self-control tasks is dependent on a physiological
  fuel: blood glucose.

  Save your Willpower: focus on using it to change your Environment,
  and you’ll have more available to use whenever Inhibition is
  necessary.

  Instead of being a single State of Being, “being happy” is a
  combination of “having fun,” “spending time with people I enjoy,”
  “feeling calm,” and “feeling free.”

  Decide what States of Being you want to experience, and you’ll
  have a powerful set of decision criteria you can use to evaluate
  the results of your actions in an entirely new and useful way.

  Experimentation is the essence of living a satisfying, productive,
  fulfilling life. The more you Experiment, the more you learn, and
  the more you’ll achieve.


** Take care of yourself
   Your brain and body simply aren’t optimized for the modern world.
   Part of the challenge of working in the modern world is that our
   brains and bodies are tuned for physical and social survival, not
   sixteen-hour workdays.

   If you want to do good work, taking care of yourself isn’t
   optional.

   It’s not—taking care of yourself should be your primary concern if
   you want to get important things done without burning out.

   Eat high-quality food. Garbage In, Garbage Out

   Get at least seven to eight hours of sleep each night.

   Feed your brain the raw materials it needs to run.

   At the core is a structure called the hindbrain, which is
   essentially responsible for keeping you alive.

   Above your hindbrain is the midbrain, which is responsible for
   processing sensory data, emotion, memory, and Pattern Matching

   Sitting just above the midbrain is a thin, folded layer of
   tissue—the forebrain. This small sheet of neural matter is
   responsible for the cognitive capabilities that make us distinctly
   human: self-awareness, logic, deliberation, Inhibition, and
   Decision.

   A few moments of quiet meditation every day can be the difference
   between feeling scared and overwhelmed and feeling in control of
   your destiny.

** Lazyness
   Everyone’s favorite character flaw: procrastination.

   Here’s a universal truth of human
   nature: people are generally lazy. The critical insight is that
   being lazy is a feature, not a bug. Think what would happen if one
   of your ancient ancestors ran around all day for no good reason
   until they collapsed from exhaustion? If a predator or enemy
   appeared, they’d have no reserves left to respond to the threat—a
   very bad situation. As a result, we’ve evolved to avoid expending
   energy unless absolutely necessary, which I call Conservation of
   Energy. Over the past several decades, researchers have studied
   marathoners and ultramarathoners (people who regularly run fifty
   to one hundred miles at a stretch) to learn more about how the
   body responds to pain. Here’s what they’ve found: when you’re so
   tired that it feels like you’re about to kick the bucket any
   second, physiologically, you’re not even remotely close to
   actually dying. The signals your brain is sending to your body are
   a ruse that serves as a warning, prompting you to keep some energy
   in reserve, just in case energy is needed later. Unless a
   Reference Level is violated, people generally will Conserve Energy
   by not acting. Think of two roommates who share different
   standards of household cleanliness. To one, the presence of dirty
   dishes in the sink is a problem—in his mind, any dishes at all is
   “out of control,” which prompts action to fix the situation. To
   the other roommate, the situation may not be out of control until
   the sink is overflowing, at which point he’ll expend some energy
   washing dishes. Different Reference Levels, different actions. If
   you think your weight, health, and physique are just fine, you
   probably won’t change your diet or start exercising spontaneously.
   If you’re comfortable with your social circle and confidence, you
   probably won’t do much to improve your social skills or expand
   your circle of acquaintances. If you think you’re making enough
   money, you probably won’t do much to earn more. Conservation of
   Energy explains why some people stay in dead-end jobs for decades,
   even though they know the position isn’t great. If the work is
   okay, the bills get paid, and the job never becomes stressful or
   frustrating enough to violate expectations, people generally won’t
   go out of their way to get a promotion, find another job, or start
   a new business. People only start to expend effort if their
   Reference Levels are violated in some way, so if their
   expectations aren’t violated, they simply don’t act. Sources of
   information that change your Reference Levels are valuable in
   prompting action. One of the things that prompted me to build
   courses and offer consulting was the knowledge that some business
   authors and coaches were able to spend all day learning and
   helping others, and be paid very well for their expertise. That
   was enough to violate my Reference Levels about work at the
   time—if they could get paid for doing what I loved to do, why
   should I have to spend all day in a day job that was just “okay”?
   The more I learned about what people did to make this possible,
   the more I wanted to do to make it a reality for myself. Before
   Roger Bannister’s record-breaking performance in 1954, running a
   mile in under four minutes was considered beyond the physical
   limitations of the human body. After Bannister proved it was
   possible, the psychological barrier was broken: by the end of
   1957, sixteen runners had accomplished the feat. The only thing
   that changed was the Reference Level: these athletes knew it was
   possible and wanted to do it, so they did. Good books, magazines,
   blogs, documentaries, and even competitors are valuable if they
   violate your expectations about what’s possible. When you discover
   that other people are actually doing something you previously
   considered unrealistic or impossible, it changes your Reference
   Levels in a very useful way. All you need to know is that
   something you want...

** Changing
   Guiding Structure means the structure of your Environment is the
   largest determinant of your behavior. If you want to successfully
   change a behavior, don’t try to change the behavior directly.
   Change the structure that influences or supports the behavior, and
   the behavior will change automatically. If you don’t want to eat
   ice cream, don’t buy it in the first place.

** Motivation
   Motivation is an emotional state that links the parts of our brain
   hat feel with the parts that are responsible for action.

   Motivation into two basic desires: moving toward things that are
   desirable and moving away from things that aren’t.

** Threat
   Threat Lockdown is a constructive response designed to help you
   defend yourself, but like many ancient instincts, it often
   malfunctions in our modern environment. The threats you face are
   far less acute today, but they are often chronic.

   Notice the threat signal, then do what you can to prove to your
   mind the threat no longer exists, and you’ll break yourself out of
   Threat Lockdown.

** Absence Blindness
   Absence Blindness is a cognitive bias that prevents us from
   identifying what we can’t observe.

   The only reliable way I’ve found to overcome Absence Blindness is
   Check-listing (discussed later). By thinking in advance what you
   want something to look like and translating that into visible
   reminders you can refer to while making decisions, checklists can
   help you remember to look for the absence of qualities in the
   moment.

** Monoidealism
   Monoidealism is the state of focusing your energy and attention on
   only one thing, without conflicts.

   First, eliminate potential distractions and interruptions.

   As little as ten minutes of simple meditation every day can
   dramatically improve your ability to focus.

   Attention, you’re forcing your brain to spend time and effort
   thrashing, loading and reloading contexts over and over again.
   That’s why it’s possible to spend an entire day multitasking, get
   nothing done, and feel exhausted at the end—you’ve burned all of
   your energy context-switching instead of making progress. The
   Cognitive Switching Penalty is a Friction cost (discussed later):
   the less you switch, the lower the cost. That’s why Monoidealism
   is so efficient—by

   To avoid unproductive context switching, a batching strategy is
   best.

   Eliminate unproductive context switching, and you’ll get more done
   with less effort.

** MIT
   A Most Important Task (MIT) is a critical task that will create
   the most important results you’re looking to achieve.

   At the beginning of every day, create a list of two or three MITs,
   then focus on getting them done as quickly as possible. Keep this
   list separate from your general to-do list or task tracking
   system. I typically use a 3 × 5 index card or David Seah’s
   “Emergent Task Planner,”7 a free downloadable PDF

   Self-Elicitation question: “What are the two or three most
   important things that I need to do today?

   Combining this technique with Parkinson’s Law (discussed later) by
   setting an artificial deadline is extremely effective. If you set
   a goal to have all of your MITs done by 10:00 a.m., you’ll be
   amazed at how quickly you can complete the day’s most important
   tasks.

   Achieve your MITs as quickly as possible, and then you’ll have the
   rest of the day to handle anything else that comes up.

** Delegation
   There are really only four ways to “do” something: completion,
   deletion, delegation, and deferment.

   Delegation—assigning the task to someone else—is effective for
   anything another person can do 80 percent as well as you can.

   Deferment—putting the task off until later—is

** Goals
   Well-formed Goals accomplish two things: they help you visualize
   what you want and make you excited about achieving it.

   makes it easy for your brain to use Mental Simulation to Visualize
   what achieving that Goal looks like.

   Goals are most useful if they’re Framed in a Positive, Immediate,
   Concrete, Specific (PICS) format:

   Positive refers to Motivation—your Goal should be something you
   move toward, not away from. Goals like “I don’t want to be fat
   anymore” are a recipe for Threat Lockdown—you’re

   Immediate refers to time scale: your Goals should be things that
   you decide to make progress on now, not “someday” or “eventually.”

   Concrete means you’re able to see the results in the real world.

   Specific means you’re able to define exactly what, when, and where
   you’re going to achieve your Goal.

   It’s perfectly okay to change your Goals. Sometimes we think we
   want something, only to find out later that we don’t want it so
   much anymore. Don’t feel bad about that—it’s called learning.

** Habits
   Habits are regular actions that support us.

   Due to the power of Accumulation, small Habits can add up to huge
   results over time.

   focus on installing one Habit at a time.

   Focus on installing one Habit until taking action feels automatic,
   then move on to the next.

   Connect your big Goals to small actions you can take now, and
   you’ll inevitably achieve what you set out to accomplish.

   Make it a Habit to consistently ask yourself good questions, and
   you’ll be surprised how easy it is to overcome the challenges you
   face.

** Priming
** Decisions
   Collect just enough information to make an informed decision, then
   make your Decision and move forward. Failure to make a Decision is
   itself a decision. Life doesn’t stop if you refuse to choose—the
   world will keep moving forward, and you may be forced to take
   action by default. Abdicating responsibility for your Decisions
   doesn’t mean you’re not making them—you’re just allowing yourself
   to be a victim of circumstance.
** You are wrong
** Five Fold Why

   The Five-Fold Why is a technique to help you find out what you actually want.
   Applying it is easy: whenever you want something, ask yourself “Why?” as many times as needed until you get to the root of the want.
   Discover the root causes behind the want, and you’ll discover new ways to get there.

   Questions for Consideration:

   Look at your current goals – are they ends in themselves, or could there be deeper reasons behind your desires?
   How can you use the Five-Fold Why to discover the root causes behind your goals?
** Testing
   The most happy and productive people I know all have something in
   common: they’re always trying new things to see what works.
** Growth Mindset
   The second basic mind-set is that your skills and abilities are
   malleable. If you try something and it doesn’t work, it’s because
   you haven’t worked on it very much, but if you keep trying, you’ll
   inevitably get better. Your skills and abilities are like
   muscles—they strengthen with use. Using the Growth Mind-set, if
   you experience a challenge or difficulty, you’re likely to keep
   going—you might not be good at it yet, but you’re always getting
   better.

   Viewing your mind as a muscle is the best way to help it grow.

* Properties
** Throughput

   Throughput is the rate at which a system achieves its desired
   goal.

   The best way to begin increasing Throughput is to start measuring
   it. How long does it take for your business system to produce a
   dollar of profit? How long does it take to produce another unit to
   sell, or a new happy customer?

** Duplication
   Duplication is the ability to reliably reproduce something of
   value.

** Multiplication
   Multiplication is Duplication for an entire process or System.

** Scale
   Scale is the ability to reliably Duplicate or Multiply a process
   as volume increases.

   Small helpful or harmful behaviors and inputs tend to Accumulate
   over time, producing huge results.

* Tools
  Always choose the best tools that you can obtain and afford.
  Quality tools give you maximum output with a minimum of input. By
  investing in Force Multipliers, you free up your time, energy, and
  attention to focus on building your business instead of simply
  operating it.

  A System is a process made explicit and repeatable—a series of
  steps that has been formalized in some way.

  Actually, useful systems make your work easier—if you’re feeling
  overloaded, the best thing you can do to solve the issue is spend
  time creating good systems.

* Funding
  Personal Cash is by far the best form of financing.

  Personal Credit is another low-cost method of financing.

  Personal Loans are typically made by friends and family.

  Unsecured Loans are typically made by banks and credit unions.

  Secured Loans require collateral. Mortgages and automotive loans
  are good examples of secured loans:

  Bootstrapping is the art of building and operating a business
  without Funding.



  Bonds are debt sold to individual lenders. Instead of asking a
  bank for a loan directly, the business asks individuals or other
  companies to loan them money directly.

  Receivables Financing is a special type of secured lending unique
  to businesses. Receivables Financing can make millions of dollars
  in credit available, but at a cost: the collateral for the loan is
  control over the business’s receivables.

  Angel Capital is where we shift from Loans to Capital. An “angel”
  is an individual private investor—someone who has excess wealth
  they’d like to invest in a private business,

  Venture Capital takes over where angels leave off. Venture
  Capitalists (VCs) are extremely wealthy investors (or groups of
  investors who pool their funds) with very large sums of Capital
  available: tens (or hundreds) of millions of dollars in a single
  investment.

  A Public Stock Offering involves selling partial ownership of the
  company to investors on the open market.

  Investors can collect their returns in one of two ways: reaping
  dividends that distribute the Profits of the company or selling
  their shares to another investor.

  Investors increase Communication Overhead

  Funding can help you do things that would otherwise be impossible
  with your current budget.

  In order to obtain access to Funding, it’s often necessary to give
  up a certain amount of control over the business’s operations.

* Finance

  Finance is the art and science of watching the money flowing into
  and out of a business, then deciding how to allocate it and
  determining whether or not what you’re doing is producing the
  results you want.

  Believe it or not, there are only four ways to increase your
  business’s revenue:

  + Increase the number of customers you serve.
  + Increase the average size of each Transaction by selling more.
  + Increase the frequency of transactions per customer.
  + Raise your prices.

  If you have a choice, choose a market in which you’ll have Pricing
  Power—it’ll be much easier to maintain Sufficiency over time.

  Many businesses have closed with millions of dollars of “sales” on
  the books.

** Profit
   Profit is a very simple concept: it’s bringing in more money than
   you spend.

** Value capture
   Value Capture is the process of retaining some percentage of the
   value provided in every Transaction.

** Sufficiency
   Sufficiency is the point where a business is bringing in enough
   profit that the people who are running the business find it
   worthwhile to keep going for the foreseeable future.

   Once you reach the point of Sufficiency, you’re successful. No
   matter how much (or how little) money you make.

** Debt
   Debt is a promise you make to pay someone at a later date.

** Overhead
   Overhead represents the minimum ongoing resources required for a
   business to continue operation.

** Costs
   Reductions in Fixed Costs Accumulate; reductions in Variable Costs
   are Amplified by volume. If you can save $50 per month on your
   phone bill, that savings Accumulates to $600 per year. If you can
   save $0.50 on each T-shirt you produce, you’ll save $500 on every
   1,000 T-shirts you make.

   Control your costs, but don’t undermine the reason customers buy
   from you in the first place.

** Breakeven
   Breakeven is the point where your business’s total revenue exceeds
   its total expenses—it’s the point where your business starts
   creating wealth instead of consuming it.

** Lot of money
   Is $10,000 a lot of money? It depends on your circumstances. If
   you have $10 in your bank account, $10,000 is an enormous sum. If
   you have $100,000,000, it’s a rounding error.

** Amortization
   Amortization is the process of spreading the cost of a resource
   investment over the estimated useful life of that investment.

   Using Amortization to figure out whether or not a big investment
   is worth it is smart—just remember you’re making a prediction, and
   proceed accordingly.
** Purchasing power
   Purchasing Power is the sum total of all liquid assets a business
   has at its disposal. That includes your cash, credit, and any
   outside financing that’s available.

   The more Purchasing Power you have, the more Resilient (discussed
   later) your business is and the better your ability to handle the
   unexpected.


** Receivables
   Receivables are promises of payment you’ve accepted from others.

** Opportunity Cost
   Opportunity Cost is the value you’re giving up by making a
   Decision.
** Compounding
   Compounding is the Accumulation of gains over time. Whenever
   you’re able to reinvest gains, your investment will build upon
   itself exponentially—a positive Feedback Loop (discussed later).
** Return on Investment
   Return on Investment (ROI) is the value created from an investment
   of time or resources.
** Leverage
   Leverage is the practice of using borrowed money to magnify
   potential gains.
** Sunk Costs
   Sunk Costs are investments of time, energy, and money that can’t
   be recovered once they’ve been made.

* Time
  Calculating the Time Value of Money is a way of making Decisions
  in the face of Opportunity Costs. Assuming you have various
  options of investing funds with various returns, the Time Value of
  Money can help you determine which options to choose and how much
  you should spend, given the alternatives.

  The central insight that a dollar today is worth more than a
  dollar tomorrow can be extended to apply to many common financial
  situations.

  Ingvar Kamprad, the founder of IKEA, once said, “If you split your
  day into ten-minute increments, and you try to waste as few of
  those ten-minute increments as possible, you’ll be amazed at what
  you can get done.”

* Success
  Whenever an individual or a business decides that success has been
  attained, progress stops.
* Stop
  Don’t continue to pour concrete into a bottomless pit—if it’s not
  worth the additional investment, walk away.
* Perception
  Reference Level is a range of perceptions that indicate the system is
  “under control.”

  There are three kinds of Reference Levels: set points, ranges, and
  errors.

  A set point is a minimum or maximum value. The thermostat is an
  example of a set point—whenever

  Business financial controls are managed as set points: as long as
  your revenue is above a certain set point and your expenses are
  below a certain set point, you’re okay.

  A range is a spread of acceptable values. The difference between a
  range and a set point is the existence of an upper and lower limit
  to the perception being controlled. With a set point, the
  perception must be above or below a certain level to be under
  control; with a range, the perception must be between two set
  points to be under

  An error is a set point defined as zero—any perception that’s not
  zero is out of control. Think of the pain receptors in your skin.
  Most of the time, they do nothing, which means everything is under
  control.

  Consciously defining and redefining Reference Levels can help you
  change your behavior.

  Change the Reference Level, and your behavior will change
  automatically.

* Reorganization
  Reorganization is random action that occurs when a Reference Level
  is violated but you don’t know what to do to bring the perception
  back under control.

  Reorganization is for—it’s the impulse to consider or try new
  things to see what works.
* Conflict
  Conflicts occur when two control systems try to change the same
  perception.

  Change the situation that creates the Reference Levels each party
  is using to measure success, and you’ll eliminate the Conflict.

  humans have the cognitive capacity to keep track of somewhere
  around 150 close personal connections. Beyond this limited circle,
  we start treating people less like individuals and more like
  objects, and groups of people beyond this limit are likely to
  splinter off into subgroups over time.

  There’s some controversy regarding the actual quantity of
  connections where Cognitive Scope Limitation kicks in (the
  Bernard-Killworth median, a competing estimate, is 231), but
  there’s little doubt that such a limit exists.

  As a result, your mind effortlessly forms Associations—even
  between things that aren’t logically connected.

  Everyone knows James Bond is a fictional character, but when
  Daniel Craig is featured wearing a tuxedo in a watch
  advertisement, the “sophisticated international spy” Association
  is automatically transferred to the timepiece. Cultivate the right
  Associations, and potential customers will want what you have even
  more.

* Relationships
  All human relationships are based on Power—the ability to
  influence the actions of other people.

  The use of Power typically takes one of two fundamental forms:
  influence or compulsion. Influence is the ability to encourage
  someone else to want what you suggest. Compulsion is the ability
  to force someone else to do what you command.

  On the whole, influence is much more effective than compulsion.

  The best way to increase your Power is to do things that increase
  your influence and Reputation. The more people know your
  capabilities and respect the Reputation you’ve built, the more
  Power you will have.

  Focus on what you can do well, and work with others to accomplish
  the rest.

  The more Important you make people feel when they’re around you,
  the more they’ll like you and want to be around you.

  Here’s a fascinating quirk about asking people to do something:
  they’ll be far more likely to comply with your request if you give
  them a reason to do what you ask.

  Jim Rohn, author of The Art of Exceptional Living, “You are the
  average of the five people you spend the most time with.”

  Let others know you expect great work from them, and they’ll do
  their best to live up to your expectations.

* Team
  Communication Overhead is the proportion of time you spend
  communicating with members of your team instead of getting
  productive work done.

  If you’re responsible for working with a group of more than five
  to eight people, at least 80 percent of your job will inevitably
  be communicating effectively with the people you work with.

  If you want your team to perform at its best, make your teams as
  small and autonomous as possible.

  The more people available, the less responsibility each member of
  the crowd feels to do anything about the situation.


  Based on what we’ve learned thus far, here are six simple
  principles of effective real-world Management:
  1. Recruit the smallest group of people who can accomplish what must be done
  quickly and with high quality. Small, elite teams are best.
  2. Clearly communicate the desired End Result, who is responsible
     for what, and the current status.
  3. Treat people with respect.
  4. Create an Environment where everyone can be as productive as
     possible
  5. Refrain from having unrealistic expectations regarding certainty and
     prediction.
  6. Measure to see if what you’re doing is working—if not, try another approach.

* Auto-catalysis
  Auto-catalysis is a concept that comes from chemistry: it’s a
  reaction whose output produces the raw materials necessary for an
  identical reaction.

  Every time someone signs up for Facebook, they’ll naturally invite
  even more users to the network. Every time someone sees a funny
  video on YouTube, they’ll pass it along to several friends. That’s
  Autocatalysis. If your business includes some Autocatalyzing
  element, it’ll grow more quickly than you expect.

* Flexible
  The more flexible you are, the more Resilient (discussed later)
  you’ll be when things inevitably Change.
* Optimize
  By definition, if you’re trying to Maximize or Minimize more than
  one thing, you’re not Optimizing—you’re making Trade-offs.

  Remember: you can’t reliably Optimize a system’s performance
  across multiple variables at once. Pick the most important one and
  focus your efforts accordingly.

  If your Goal is to make the system faster or more efficient,
  Refactoring is critically important.

  This Pattern of persistent nonlinearity is now called the Pareto
  principle, or the 80-20 rule. Personally, I prefer to refer to it
  as the Critical Few.

  Optimize and Refactor up to the point you start experiencing
  Diminishing Returns, then focus on doing something else.

* Automation
  Here’s the Paradox of Automation: the more efficient the Automated
  system, the more crucial the contribution of the human operators
  of that system.

  Efficient Automation makes humans more important, not less.

  Here’s the Irony of Automation: the more reliable the system, the
  less human operators have to do, so the less they pay Attention to
  the system while it’s in operation.
* Nothing
  Sometimes the best way to improve a System is to stop doing so
  much. Cessation is the choice to intentionally stop doing
  something that’s counterproductive.

  Doing something is not always the best course of action. Consider
  doing nothing instead.
* Procedures
  Create Standard Operating Procedures for important recurring
  tasks, and you’ll see your productivity skyrocket.
